// <auto-generated />
namespace TaskAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fistmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fistmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110454142_fist-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
